name: docs-build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@0cc5a2cfcb939086d9d4972ac3f17aedd1679140 # v1
