name: docs-preview-cleanup
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@0cc5a2cfcb939086d9d4972ac3f17aedd1679140 # v1
